### ISSUE TITLE
İnformation

### ISSUE THREAD

**Issue by briusxD** [briusxD/Redeem#3]
### config.yml
```
# Plugin made by devbrius
# Discord: devbrius
# Github: https://github.com/briusxD/Redeem
# Language option Turkish "tr", English "en"
locale: tr

# codes option "1250:ABCDEFGHI" or "ABCDEFGHI:1250"
codes:
  '1250':
    - ABCDEFGHI
    - JKLMNOPQR
  '750':
    - STUVWXYZA
    - XYZ123456
  '500':
    - ABC987654
  '250':
    - CODE001
  '100':
    - CODE003
  CODE003: 100
  STUVWXYZA: 750
  XYZ123456: 750
  ABC987654: 500
  ABCDEFGHI: 1250
  JKLMNOPQR: 1250
  CODE001: 250

# used codes list in here
used_codes: []
```

###  messages_en.yml

```
errors:
  no_permission: "&d&lINFO &7: &dYou do not have permission to use this command."
  incorrect_usage: "&d&lINFO &7: &dIncorrect usage! Correct usage: /redeem <code>"
  invalid_code: "&d&lINFO &7: &dInvalid code!"
  code_used: "&d&lINFO &7: &dThis code has already been used!"
help:
  header: "&d&lREDEEM PLUGIN HELP"
  usage: "&d/redeem <code> &7: &dAllows you to earn points with a code."
success:
  redeemed: "&d&lINFO &dCongratulations! You earned %points% points."

```
